# Generated by Django 3.2.5 on 2022-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
